baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'



[module]
[[module.imports]]
  path = 'github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy'
[[module.imports]]
  path = 'github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal'
